name: Persubmit Checks
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  run_tests:
    name: Run Tests
    strategy:
      matrix:
        taichi:
          - 0.7.18
        python:
          - 3.6
          - 3.7
          - 3.8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Requirements
        run: |
          pip install taichi==${{ matrix.taichi }}
          pip install pytest coverage

      - name: Functionallity Test
        run: |
          export PYTHONPATH=`pwd`
          coverage run -m pytest tests

      - name: Upload to Codecov
        if: ${{ matrix.python == '3.8' }}
        run: |
          coverage report
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  check_format:
    name: Check Code Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install YAPF
        run: |
          pip install yapf

      - name: Run YAPF
        run: |
          yapf -ir .

      - name: Check Git Diff
        run: |
          git diff --exit-code
